import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-playlist-bar',
  templateUrl: './playlist-bar.component.html',
  styleUrls: ['./playlist-bar.component.scss']
})
export class PlaylistBarComponent implements OnInit {
	public playlists = [
	    { name: 'DJ Snake – Encore' },
	    { name: 'Weval – Weval' },
	    { name: 'deadmau5 – W:/2016ALBUM/' },
	    { name: 'Tycho – Elioch'},
	    { name: 'Moby – Long Ambients1: Calm. Sleep'},
	    { name: 'Childish Gambino – Awaken, My Love!'},
	    { name: 'Gabriel Garzon-Montano Bishouné: Alma Del Huila (Deluxe)'},
	    {name: 'Oneohtrix Point Never – R Plus Seven'},
	    {name: 'AlunaGeorge – I Remember'},
	    {name: 'Justice – Woman'},
	    {name: 'This is: David Mancuso'},
	    {name: 'A Tribe Called Quest – We Got It From Here ... Thank you 4 Your Service'},
	    {name: 'Youandewan – There Is No Right Time'},
	    {name: 'Radiohead – In Rainbows disk 2'},
	    {name: 'The xx – Hivern remixes'},
	    {name: 'Royksopp – Junior'},
	    {name: 'Discover Weekly'},
	    {name: 'Jim-E Stack – Tell Me I Belong'},
	    {name: 'Twenty One Pilots – Blurryface'},
	    {name: 'Deep House Relax'},
	    {name: 'Convo/Chillin/High'},
	    {name: 'Dance'},
	    {name: 'Atmospheric'},
	    {name: 'Raging Energy'},
	    {name: 'Once More'},
	    {name: 'Chill Beats'},
	    {name: 'Essentials'},
	    {name: 'Chill BBQ'},
	    {name: 'Frank Ocean – Blonde'},
	    {name: 'Bon Iver – 22, A Million'},
	    {name: 'Banks – The Altar'},
	    {name: 'James Blake – Enough Thunder'},
	    {name: 'Anderson.Paak –Mailbu'},
	    {name: 'At All/ Hilarity Duff EP'},
	    {name: 'Kaskade – The Grand'},
	    {name: 'Hot House'},
	    {name: 'Jody Wisternoff – Trails We Blaze'},
	    {name: 'Tourist – U'},
	    {name: 'BadBadNotGood – IV'},
	    {name: 'BadBadNotGood – SOUR SOUL'},
	    {name: 'Above & Beyond – Acoustic II'},
	    {name: 'Flume – Skin'},
	    {name: 'Anjunadeep 07'},
	    {name: 'Anjunadeep 08'},
	    {name: 'Max Corbacho – Splendid Labyrinth'},
	    {name: 'Max Corbacho – BreathStream'},
	    {name: 'Rudy Adrian – Atmosphere'},
	    {name: 'Alternative Beats'},
	    {name: 'Radiohead – A Moon Shaped Pool'},
	    {name: 'Mediative Sleep'},
	    {name: 'KAYTRANADA – 99.9%'},
	    {name: 'James Blake – The Colour in Anything'},
	    {name: 'Kanye West – The Life of Pablo'},
	    {name: 'A$AP Ferg – Always Strive and propser'},
	    {name: 'Wild Belle – Dreamland'},
	    {name: 'Snakehips – All My Friends – EP'},
	    {name: 'K.Flay – Life as Dog (Deluxe Edition)'},
	    {name: 'Until The ribbon breaks – A Lesson Unlearnt'},
	    {name: 'Exotic Toy – ExoticToy'},
	    {name: 'Kendrick Lamar –untilied unmastered'},
	    {name: 'Macklemore & Ryan Lewis – This Unruly Mess I\'ve Made'},
	    {name: 'Productive Morning'},
	    {name: 'deadmau5 – For Lack of Better name'},
	    {name: '4am Comedown'},
	    {name: 'Muse – Drones'},
	    {name: 'Experience'},
	    {name: 'Charli XCX –Vroom Vroom EP'},
	    {name: 'Massive Attack – Ritual Spirit'},
	    {name: 'Kanye West – The Life of Pablo v1'},
	    {name: 'Programming'},
	    {name: 'Wankelmut – Wankelmoods, Vol. 2'},
	    {name: 'Kid Ink – Summer in the winter'},
	    {name: 'The Weeknd: Samples and Inspirations'},
	    {name: 'ODESZA – In Return {Deluxe Editon'},
	    {name: 'Tiésto – Kaleidoscope'},
	    {name: 'Black Star – Mos Def & Talib Kweli Are Black Star'},
	    {name: 'Drum & Bass'},
	    {name: 'Dance Hits in Belgium'},
	    {name: 'deadmau5 – 4x4=12'},
	    {name: 'Melleefresh – At Play'},
	    {name: 'Solomon Grey – Selected Works (Music From the casual vacancy)'},
	    {name: 'Various Artists – Toolroom Ibiza 2015'},
	    {name: 'Axel Thesleff – The Hollow Men'},
	    {name: 'Mileyface – Feeling Groovy: For smoke sessions only'},
	    {name: 'Daft Punk – TRON: Legacy'}

	]

  constructor() { }

  ngOnInit() {
  }

}
